version: "3.7"
services:
    db:
      image: mysql:5.7
      container_name: mysql-container
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: teste123
      ports:
        - "3306:3306"
      volumes: 
        # - ./api/db/data:/var/lib/mysql
        - ./api/db/queries:/docker-entrypoint-initdb.d/
      restart: always
    api:
      build: "./api"
      container_name: node-container
      restart: always
      volumes: 
        - ./api:/home/node/app
      ports: 
        - "9001:9001"
      depends_on: 
        - db